import type { components } from "../generated/schema";

export type RenderTarget = components["schemas"]["RenderTarget"];
export type RenderRequest = components["schemas"]["RenderRequest"];
export type RenderResponse = components["schemas"]["RenderResponse"];
export type PrintJobCreateRequest = components["schemas"]["PrintJobCreateRequest"];
export type RasterPageRequest = components["schemas"]["RasterPageRequest"];
export type RasterPrintJobCreateRequest = components["schemas"]["RasterPrintJobCreateRequest"];
export type DocumentPrintJobCreateRequest = components["schemas"]["DocumentPrintJobCreateRequest"];
export type RasterPrintJobReleaseRequest = components["schemas"]["RasterPrintJobReleaseRequest"];
export type PrintJobResponse = components["schemas"]["PrintJobResponse"];
export type PrintDraftCreateRequest = components["schemas"]["PrintDraftCreateRequest"];
export type PrintDraftResponse = components["schemas"]["PrintDraftResponse"];
export type PrintDraftDetailResponse = components["schemas"]["PrintDraftDetailResponse"];
export type TemplateSaveRequest = components["schemas"]["TemplateSaveRequest"];
export type TemplateListItem = components["schemas"]["TemplateListItem"];
export type TemplateDetailResponse = components["schemas"]["TemplateDetailResponse"];
export type PrintersConfigResponse = components["schemas"]["PrintersConfigResponse"];
export type HTTPValidationError = components["schemas"]["HTTPValidationError"];
export type ValidationError = components["schemas"]["ValidationError"];
